name: Sxift
version: ${project.version}
main: me.xyrophyte.sxift.Sxift
authors: [ XyroPhyte ]
description: Minecraft Spigot Plugin
commands:
  feed:
    description: Refills hunger.
    usage: /feed
  heal:
    description: Heals.
    usage: /heal
  kit:
    description: Get a full diamond kit.
    usage: /kit
  ping:
    description: Pong!
    aliases:
      - test
    usage: /ping
  suicide:
    description: Commit suicide.
    aliases:
      - kill
      - die
    usage: /suicide
