name: Sxift
version: ${project.version}
main: me.xyrophyte.sxift.Sxift
authors: [ XyroPhyte ]
description: Minecraft Spigot Plugin
commands:
  god:
    description: Vanish. Enter GodMode.
    aliases:
      - vanish
      - invisible

  heal:
    description: Heals.

  ping:
    description: Pong!
    aliases:
      - test

  suicide:
    description: Commit suicide.
    aliases:
      - kill
      - die
