name: Sxift
version: ${project.version}
main: me.xyrophyte.sxift.Sxift
authors: [ XyroPhyte ]
description: Minecraft Spigot Plugin
commands:
  feed:
    description: Refills hunger.
    usage: /feed
  fly:
    description: Fly.
    usage: /fly
  heal:
    description: Heals.
    usage: /heal
  kill:
    description: Kill other players or commit suicide.
    usage: /kill <player>
  kit:
    description: Get a full diamond kit.
    usage: /kit
  32k:
    description: 32k Kit
    usage: /32k
  mock:
    description: Copies whatever word you say.
    usage: /mock
  ping:
    description: Pong!
    aliases:
      - test
    usage: /ping
  suicide:
    description: Commit suicide.
    aliases:
      - kill
      - die
    usage: /suicide
  trash:
    description: Opens a trash can where you can throw trash.
    usage: /trash