name: Sxift
version: ${project.version}
main: me.xyrophyte.sxift.Sxift
authors: [ XyroPhyte ]
description: Minecraft Spigot Plugin
commands:
  god:
    description: Vanish. Enter GodMode.
    aliases:
      - vanish
      - invisible
    usage: /god

  heal:
    description: Heals.
    usage: /heal

  ping:
    description: Pong!
    aliases:
      - test
    usage: /ping

  suicide:
    description: Commit suicide.
    aliases:
      - kill
      - die
    usage: /suicide
